spring:
  liquibase:
    change-log: classpath:liquibase/main.yml
    contexts: main
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:clients;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

countries-api:
  url: https://restcountries.eu/rest/v2/

api:
  documentation:
    title: Demo service to register EU clients
    description: Provides integration with restcountries service
    version: 1
    pathMapping: /
    contact:
      name: Aleksandrs Rihļiks
      email: aleksandrs.rihliks@gmail.com